admin/urls.py
from django.urls import path

app_name = "admin"

urlpatterns = [

]

avis/urls.py
from django.urls import path

from temps_reel.urls import app_name

app_name = "avis"

urlpatterns = [

]

kovoit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateur.urls')),
    path('avis/', include('avis.urls')),
    path('payement/', include('payement.urls')),
    path('temp_reel/', include('temps_reel.urls')),
    path('trajet/', include('trajet.urls')),
    path('administateur/', include('admin.urls')),
]

payement/urls.py
from django.urls import path

app_name = 'payement'

urlpatterns = [

]

temps_reel/urls.py
from django.urls import path

app_name = 'temps_reel'

urlpatterns = []

trajet/urls.py
from django.urls import path

app_name = "trajet"
urlpatterns = [

]

utilisateur/urls.py
from django.urls import path
from . import views

app_name = 'utilisateur'

urlpatterns = [
    #acceuil
    path('', views.splash, name='splash'),
    path('home/kovoit/', views.home, name='home'),


    #inscription
    path("inscritption/", views.inscription, name='inscription'),
    path("commpte/creer/", views.compte_create, name='compte_creer'),

    #connection
    path('bienvenue/', views.welcome, name='welcome'),
    path('connection/phone/', views.connection_phone, name='connection_phone'),
    path('verification/phone/', views.verification_phone, name='verification_phone'),
    path('connection/reussi/', views.connection_reussi, name='connection_reussi')
]

admin/models.py
from django.db import models

# Create your models here.

models/apps.py
from django.apps import AppConfig


class ModelsConfig(AppConfig):
    name = 'models'

admin/views.py
from django.shortcuts import render

# Create your views here.

utilisateur/views.py
from django.shortcuts import render, redirect


def splash(request):
    return render(request, 'splash.html')

"""login"""
def welcome(request):
    return render(request, 'login/welcome.html')

def connection_phone(request):
    return render(request, "login/loginwithmobile.html")

def verification_phone(request):
    return render(request, "login/otpverification.html")

def connection_reussi(request):
    return render(request, "login/accountconnect.html")


"""inscription"""

def inscription(request):
    return render(request, "inscription/inscription.html")

def compte_create(request):
    return render(request, "inscription/accountcreated.html")

"""acceuil"""

def home(request):
    return render(request, "home.html")

"""logout"""

templates/splash.html
<!doctype html>
<html lang="en">
  <!-- Mirrored from taxi-mode.vercel.app/splash.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 13 Feb 2026 10:31:15 GMT -->
  <!-- Added by HTTrack --><meta
    http-equiv="content-type"
    content="text/html;charset=utf-8"
  /><!-- /Added by HTTrack -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- PWA Manifest File -->
    <link
      rel="manifest"
      href="manifest.json"
      data-pwa-version="set_in_manifest_and_pwa_js"
    />
    <!-- Mobile Specific Metas -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, viewport-fit=cover"
    />
    <!-- SEO Informations -->
    <title>TaxiMode - Taxi Booking App | Splash</title>
    <meta
      name="description"
      content="TaxiMod - Taxi Booking Mobile PWA HTML Template"
    />
    <meta
      name="keywords"
      content="TaxiMode, Taxi Booking Mobile PWA HTML Template, Taxi Services App, PWA Mobile Template, TaxiMode PWA Progressive Web Application, Taxi Services Progressive Web Application"
    />
    <meta name="author" content="Shreyanshi Infotech" />
    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="img/favicon.ico" />
    <link
      rel="android-chrome-icon"
      sizes="72x72"
      href="img/android-chrome-72x72.png"
    />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="img/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="img/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="img/favicon-16x16.png"
    />
    <!--- CSS File --->
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="css/custom.css" rel="stylesheet" type="text/css" />
  </head>

  <body class="m-0 p-0">
    <!-- Start Preloader -->
    <div class="loader-mask">
      <div class="pre-loader">
        <div></div>
        <div></div>
      </div>
    </div>
    <!-- End Preloader -->
    <!--- Start Splash Content --->
    <div class="container justify-content-center px-0">
      <div class="vh-100 tm-secondary-bg-color">
        <div class="text-center fixed-bottom mb-5">
          <a href="{% url 'utilisateur:welcome' %}" target="_self">
            <img src="img/logo-taximode.svg" alt="TaxiMode" title="TaxiMode" />
          </a>
        </div>
      </div>
    </div>
    <!--- End Splash Content --->
    <!--- Start External JS File -->
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="js/popper.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <!--- End External JS File -->
    <!--- Start Preloader Script -->
    <script type="text/javascript">
      $(window).load(function () {
        $(".loader").fadeOut();
        $(".loader-mask").delay(250).fadeOut("slow");
      });
    </script>
    <!--- End Preloader Script -->
    <!--- Start PWA Script Progressive Web App -->
    <script type="text/javascript">
      if ("serviceWorker" in navigator) {
        window.addEventListener("load", () => {
          navigator.serviceWorker
            .register("service-worker.js")
            .then((registration) => {
              console.log(
                "Service Worker registered with scope:",
                registration.scope,
              );
            })
            .catch((error) => {
              console.error("Service Worker registration failed:", error);
            });
        });
      }
    </script>
    <!--- End PWA Script Progressive Web App -->
  </body>

  <!-- Mirrored from taxi-mode.vercel.app/splash.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 13 Feb 2026 10:31:28 GMT -->
</html>

utilisateur/templates/inscription/inscription.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

utilisateur/templates/login/accountconnect.html
<!doctype html>
<html lang="en">
  <!-- Mirrored from taxi-mode.vercel.app/accountcreated.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 13 Feb 2026 10:31:51 GMT -->
  <!-- Added by HTTrack --><meta
    http-equiv="content-type"
    content="text/html;charset=utf-8"
  /><!-- /Added by HTTrack -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- PWA Manifest File -->
    <link
      rel="manifest"
      href="manifest.json"
      data-pwa-version="set_in_manifest_and_pwa_js"
    />
    <!-- Mobile Specific Metas -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, viewport-fit=cover"
    />
    <!-- SEO Informations -->
    <title>TaxiMode - Taxi Booking App | Account Created Successfully</title>
    <meta
      name="description"
      content="TaxiMod - Taxi Booking Mobile PWA HTML Template"
    />
    <meta
      name="keywords"
      content="TaxiMode, Taxi Booking Mobile PWA HTML Template, Taxi Services App, PWA Mobile Template, TaxiMode PWA Progressive Web Application, Taxi Services Progressive Web Application"
    />
    <meta name="author" content="Shreyanshi Infotech" />
    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="img/favicon.ico" />
    <link
      rel="android-chrome-icon"
      sizes="72x72"
      href="img/android-chrome-72x72.png"
    />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="img/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="img/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="img/favicon-16x16.png"
    />
    <!--- CSS File --->
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="css/custom.css" rel="stylesheet" type="text/css" />
  </head>

  <body class="m-0 p-0">
    <!-- Start Preloader -->
    <div class="loader-mask">
      <div class="pre-loader">
        <div></div>
        <div></div>
      </div>
    </div>
    <!-- End Preloader -->
    <!--- Start Main Content --->
    <div class="container justify-content-center px-0">
      <div class="vh-100">
        <!--- Start Top Header Content --->
        <div class="top-heading-section text-center">
          <div class="head-text mt-5">
            <div class="images mb-6">
              <img src="img/icon_thumbs_up.svg" alt="image" />
            </div>
            <div class="head-title mb-text-content">
              <h1>Account Created!</h1>
            </div>
            <div class="head-sub-title padding-lr">
              <p>
                Your account has been created successfully. Press continue to
                start using app.
              </p>
            </div>
          </div>
        </div>
        <!--- End Top Header Content --->
        <!--- Start Go Button --->
        <div class="justify-content-center d-flex mt-8">
          <a href="{% url 'utilisateur:home' %}" target="_self">
            <img src="img/img-button-go.svg" />
          </a>
        </div>
        <!--- End Go Button --->
        <!--- Start Privacy Policy --->
        <div class="tm-container text-center mt-45 py-2">
          <p class="bottom font-size-13 txt-grey">
            By continue you agree that you have read and accept our
            <br />
            <a href="termsconditions.html" class="tm-primary-color fw-bold">
              <u>Terms & Conditions</u>
            </a>
            and
            <a href="privacypolicy.html" class="tm-primary-color fw-bold">
              <u>Privacy Policy</u>
            </a>
          </p>
        </div>
        <!--- End Privacy Policy --->
      </div>
    </div>
    <!--- End Main Content --->
    <!--- Start External JS File -->
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="js/popper.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <!--- End External JS File -->
    <!--- Start Preloader Script -->
    <script type="text/javascript">
      $(window).load(function () {
        $(".loader").fadeOut();
        $(".loader-mask").delay(250).fadeOut("slow");
      });
    </script>
    <!--- End Preloader Script -->
    <!--- Start PWA Script Progressive Web App -->
    <script type="text/javascript">
      if ("serviceWorker" in navigator) {
        window.addEventListener("load", () => {
          navigator.serviceWorker
            .register("service-worker.js")
            .then((registration) => {
              console.log(
                "Service Worker registered with scope:",
                registration.scope,
              );
            })
            .catch((error) => {
              console.error("Service Worker registration failed:", error);
            });
        });
      }
    </script>
    <!--- End PWA Script Progressive Web App -->
  </body>

  <!-- Mirrored from taxi-mode.vercel.app/accountcreated.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 13 Feb 2026 10:31:52 GMT -->
</html>

utilisateur/templates/login/loginwithmobile.html
<!doctype html>
<html lang="en">
  <!-- Mirrored from taxi-mode.vercel.app/loginwithmobile.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 13 Feb 2026 10:31:42 GMT -->
  <!-- Added by HTTrack --><meta
    http-equiv="content-type"
    content="text/html;charset=utf-8"
  /><!-- /Added by HTTrack -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- PWA Manifest File -->
    <link
      rel="manifest"
      href="manifest.json"
      data-pwa-version="set_in_manifest_and_pwa_js"
    />
    <!-- Mobile Specific Metas -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, viewport-fit=cover"
    />
    <!-- SEO Informations -->
    <title>TaxiMode - Taxi Booking App | Login With Mobile Number</title>
    <meta
      name="description"
      content="TaxiMod - Taxi Booking Mobile PWA HTML Template"
    />
    <meta
      name="keywords"
      content="TaxiMode, Taxi Booking Mobile PWA HTML Template, Taxi Services App, PWA Mobile Template, TaxiMode PWA Progressive Web Application, Taxi Services Progressive Web Application"
    />
    <meta name="author" content="Shreyanshi Infotech" />
    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="img/favicon.ico" />
    <link
      rel="android-chrome-icon"
      sizes="72x72"
      href="img/android-chrome-72x72.png"
    />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="img/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="img/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="img/favicon-16x16.png"
    />
    <!--- CSS File --->
    <link
      rel="stylesheet"
      href="css/intlTelInput.css"
      rel="stylesheet"
      type="text/css"
    />
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="css/custom.css" rel="stylesheet" type="text/css" />
    <style>
      .iti--separate-dial-code .iti__selected-flag {
        background-color: transparent !important;
      }
    </style>
  </head>

  <body class="m-0 p-0">
    <!-- Start Preloader -->
    <div class="loader-mask">
      <div class="pre-loader">
        <div></div>
        <div></div>
      </div>
    </div>
    <!-- End Preloader -->
    <!--- Start Main Content --->
    <div class="container justify-content-center px-0">
      <div class="vh-100">
        <!--- Start Top Header Content --->
        <div class="top-heading-section text-center">
          <div class="head-text mt-5">
            <div class="images mb-6">
              <img src="img/logo-taximode.svg" alt="image" />
            </div>
            <div class="head-title mb-text-content">
              <h1>Mobile Number</h1>
            </div>
            <div class="head-sub-title padding-lr">
              <p>
                Please enter your phone number. We will send you 4-digit code to
                verify your account.
              </p>
            </div>
          </div>
        </div>
        <!--- End Top Header Content --->
        <!--- Start Form Elements --->
        <div class="tm-container padding-lr">
          <div class="d-flex gap-3 d-flex justify-content-center">
            <div>
              <div class="floating-label mt-5">
                <div class="mb-3 floating-label">
                  <input
                    name="phone"
                    type="text"
                    id="phone"
                    class="form-control input-label-lg form-control-lg col-5"
                    style="width: 90px"
                  />
                  <!-- <label for="form-select-lg">Country</label> -->
                </div>
              </div>
            </div>
            <div>
              <div class="floating-label mt-5">
                <input
                  type="number"
                  id="text-value"
                  class="form-control input-label-lg form-control-lg col-7"
                  placeholder=" "
                  value=""
                  style="width: 230px"
                />
                <label for="text-value input-label-lg"> Phone Number</label>
              </div>
            </div>
          </div>
        </div>
        <!--- End Form Elements --->
        <!--- Start Go Button --->
        <div class="justify-content-center d-flex mt-4">
          <a href="{% url 'utilisateur:verification_phone' %}" target="_self">
            <img src="img/img-button-go.svg" />
          </a>
        </div>
        <!--- End Go Button --->
        <!--- Start Privacy Policy --->
        <div class="tm-container text-center mt-4 py-2">
          <p class="bottom font-size-13 txt-grey">
            By continue you agree that you have read and accept our
            <br />
            <a href="termsconditions.html" class="tm-primary-color fw-bold">
              <u>Terms & Conditions</u>
            </a>
            and
            <a href="privacypolicy.html" class="tm-primary-color fw-bold">
              <u>Privacy Policy</u>
            </a>
          </p>
        </div>
        <!--- End Privacy Policy --->
      </div>
    </div>
    <!--- End Main Content --->
    <!--- Start External JS File -->
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="js/popper.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script src="js/intlTelInput.min.js"></script>
    <script>
      var input = document.querySelector("#phone");
      window.intlTelInput(input, {
        separateDialCode: true,
        /*excludeCountries: ["in", "il"],*/
        preferredCountries: ["in", "jp", "pk", "no"],
      });
    </script>
    <!--- End External JS File -->
    <!--- Start Preloader Script -->
    <script type="text/javascript">
      $(window).load(function () {
        $(".loader").fadeOut();
        $(".loader-mask").delay(250).fadeOut("slow");
      });
    </script>
    <!--- End Preloader Script -->
    <!--- Start PWA Script Progressive Web App -->
    <script type="text/javascript">
      if ("serviceWorker" in navigator) {
        window.addEventListener("load", () => {
          navigator.serviceWorker
            .register("service-worker.js")
            .then((registration) => {
              console.log(
                "Service Worker registered with scope:",
                registration.scope,
              );
            })
            .catch((error) => {
              console.error("Service Worker registration failed:", error);
            });
        });
      }
    </script>
    <!--- End PWA Script Progressive Web App -->
  </body>

  <!-- Mirrored from taxi-mode.vercel.app/loginwithmobile.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 13 Feb 2026 10:31:44 GMT -->
</html>

utilisateur/templates/login/welcome.html
<!doctype html>
<html lang="en">
  <!-- Mirrored from taxi-mode.vercel.app/welcome.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 13 Feb 2026 10:31:31 GMT -->
  <!-- Added by HTTrack --><meta
    http-equiv="content-type"
    content="text/html;charset=utf-8"
  /><!-- /Added by HTTrack -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- PWA Manifest File -->
    <link
      rel="manifest"
      href="manifest.json"
      data-pwa-version="set_in_manifest_and_pwa_js"
    />
    <!-- Mobile Specific Metas -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, viewport-fit=cover"
    />
    <!-- SEO Informations -->
    <title>TaxiMode - Taxi Booking App | Welcome</title>
    <meta
      name="description"
      content="TaxiMod - Taxi Booking Mobile PWA HTML Template"
    />
    <meta
      name="keywords"
      content="TaxiMode, Taxi Booking Mobile PWA HTML Template, Taxi Services App, PWA Mobile Template, TaxiMode PWA Progressive Web Application, Taxi Services Progressive Web Application"
    />
    <meta name="author" content="Shreyanshi Infotech" />
    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="img/favicon.ico" />
    <link
      rel="android-chrome-icon"
      sizes="72x72"
      href="img/android-chrome-72x72.png"
    />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="img/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="img/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="img/favicon-16x16.png"
    />
    <!--- CSS File --->
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="css/custom.css" rel="stylesheet" type="text/css" />
  </head>

  <body class="m-0 p-0">
    <!-- Start Preloader -->
    <div class="loader-mask">
      <div class="pre-loader">
        <div></div>
        <div></div>
      </div>
    </div>
    <!-- End Preloader -->
    <!--- Start Main Content --->
    <div class="container justify-content-center px-0">
      <div class="vh-100">
        <!--- Start Welcome to TaxiMode --->
        <div class="boarding-section">
          <img src="img/img-bg-welcome.jpg" alt="img" />
        </div>
        <!--- End Welcome to TaxiMode --->
        <!--- Start Content --->
        <div class="boarding-content text-center">
          <div class="tm-container">
            <div class="boarding-title mt-40">
              <img src="img/img-welcome-text.svg" />
            </div>
            <div class="d-grid mb-3 mt-40">
              <a href="{% url 'utilisateur:connection_phone' %}" target="_self">
                <button
                  class="btn btn-primary btn-lg tm-secondary-button col-12 d-flex justify-content-center align-content-center"
                >
                  <img src="img/icon-phone.svg" class="me-2" />
                  <span>Continue with Mobile Number</span>
                </button>
              </a>
            </div>
            <div class="d-flex gap-3">
              <button
                class="btn btn-primary btn-lg col d-flex align-items-center justify-content-center tm-secondary-button"
                type="button"
                id="open_new_tab_google"
              >
                <img src="img/icon-google.svg" class="me-2" />
                <span>Google</span>
              </button>
              <button
                class="btn btn-primary btn-lg col d-flex align-items-center justify-content-center tm-secondary-button"
                type="button"
                id="open_new_tab_facebook"
              >
                <img src="img/icon-facebook.svg" class="me-2" />
                <span>Facebook</span>
              </button>
            </div>
          </div>
        </div>
        <!--- End Content --->
        <!--- Start Privacy Policy --->
        <div class="tm-container text-center mt-45 py-2">
          <p class="bottom font-size-13 txt-grey">
            By continue you agree that you have read and accept our
            <br />
            <a href="termsconditions.html" class="tm-primary-color fw-bold">
              <u>Terms & Conditions</u>
            </a>
            and
            <a href="privacypolicy.html" class="tm-primary-color fw-bold">
              <u>Privacy Policy</u>
            </a>
          </p>
        </div>
        <div>
          <!--- Start Go Button --->
          <div class="justify-content-center d-flex mt-8">
            <a href="{% url 'utilisateur:inscription' %}" target="_self">
              s'inscrire
            </a>
          </div>
          <!--- End Go Button --->
        </div>
        <!--- End Privacy Policy --->
      </div>
    </div>
    <!--- End Main Content --->
    <!--- Start External JS File -->
    <script src="../ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="js/popper.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <!--- End External JS File -->
    <!--- Start Preloader Script -->
    <script type="text/javascript">
      $(window).load(function () {
        $(".loader").fadeOut();
        $(".loader-mask").delay(250).fadeOut("slow");
      });
    </script>
    <!--- End Preloader Script -->
    <!--- Start PWA Script Progressive Web App -->
    <script type="text/javascript">
      if ("serviceWorker" in navigator) {
        window.addEventListener("load", () => {
          navigator.serviceWorker
            .register("service-worker.js")
            .then((registration) => {
              console.log(
                "Service Worker registered with scope:",
                registration.scope,
              );
            })
            .catch((error) => {
              console.error("Service Worker registration failed:", error);
            });
        });
      }
    </script>
    <!--- End PWA Script Progressive Web App -->
    <script type="text/javascript">
      $(document).ready(function () {
        $("#open_new_tab_google").click(function () {
          var go_to_url = $("#websites").find(":selected").val();
          window.open("https://www.google.co.in/", "_blank");
        });
      });
    </script>
    <script type="text/javascript">
      $(document).ready(function () {
        $("#open_new_tab_facebook").click(function () {
          var go_to_url = $("#websites").find(":selected").val();
          window.open("https://www.facebook.com/login/", "_blank");
        });
      });
    </script>
  </body>

  <!-- Mirrored from taxi-mode.vercel.app/welcome.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 13 Feb 2026 10:31:40 GMT -->
</html>